### ISSUE TITLE
Sidebar menu always open/No hamburger icon

### ISSUE THREAD

**Issue by EduardoSaverin** [pusher/react-slack-clone#26]
Tested on Iphone 6/7/8 Sidebar Room creation menu always open + No hamburger icon
Galaxy S5 -  No hamburger icon hence can't open sidebar

**Comment by lukejacksonn** [comment]
I have been testing on iPhone 7 and can open/close the menu and see the icon. Have you got a screenshot of this happening?

**Comment by EduardoSaverin** [comment]
Sorry forgot to mention i was trying in landscape mode.

**Comment by lukejacksonn** [comment]
Ahh right. This is (for better or worse) by design, at least for the moment. Landscape support on mobile was not made a priority for initial release. Slack for instance, do not support landscape in their app AFAIK. So the fact it was usable at all in landscape on mobile is good enough for me for now.

I will add this issue to the backlog and listen out for any more feedback.

Thanks 🙇
